In [1]:
import numpy as np

## **Vectors**

### **1. Vector Addition**

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

r = a + b
print(r)

[5 7 9]


### **2. Vector Subtraction**

In [3]:
r = a - b
print(r)

[-3 -3 -3]


### **3. Dot Product**

In [4]:
d1 = np.dot(a , b) # Both are same method
d2 = a @ b

print(d1)
print(d2)

32
32


### **4. Magnitude (Norm)**

In [6]:
magnitude = np.linalg.norm(a)
print(magnitude)

3.7416573867739413


### **5. Distance Between Vectors**

In [7]:
distance = np.linalg.norm((a-b))
print(distance)

5.196152422706632


## **Matrices**

In [9]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

### **1. Matrix Addition**

In [10]:
r = A + B
print(r)

[[ 6  8]
 [10 12]]


### **2. Matrix Multiplication**

In [11]:
r1 = np.matmul(A , B)
r2 = A @ B
print(r1)
print(r2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### **3. Transpose**

In [12]:
t1 = A.T
t2 = np.transpose(A)
print(t1)
print(t2)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


### **4. Determinant**

In [13]:
det = np.linalg.det(A)
print(det)

-2.0000000000000004


### **5. Inverse**

In [14]:
inverse = np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


### **6. Eigenvalues & Eigenvectors**

In [15]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


| Operation                | Function                 |
| ------------------------ | ------------------------ |
| Vector Addition          | `a + b`                  |
| Vector Subtraction       | `a - b`                  |
| Dot Product              | `np.dot(a,b)` or `a @ b` |
| Magnitude                | `np.linalg.norm(a)`      |
| Distance                 | `np.linalg.norm(a-b)`    |
| Matrix Addition          | `A + B`                  |
| Matrix Multiplication    | `A @ B`                  |
| Transpose                | `A.T`                    |
| Determinant              | `np.linalg.det(A)`       |
| Inverse                  | `np.linalg.inv(A)`       |
| Eigenvalues/Eigenvectors | `np.linalg.eig(A)`       |
| Solve Ax=b               | `np.linalg.solve(A,b)`   |
