# 03_Matrices

## 10. NumPy Matrix Operations

> This notebook summarizes the most common matrix operations you'll use in AI/ML with NumPy.

---

## Formula

There is **no new mathematical formula**.

This topic focuses on implementing matrix operations using NumPy.

---

## Explanation

NumPy provides built-in functions for almost every matrix operation.

The most common operations are:

* Create a matrix
* Check shape
* Matrix addition
* Scalar multiplication
* Matrix multiplication
* Transpose
* Identity matrix
* Diagonal matrix
* Access rows, columns, and elements

---

## Example

```python
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
```

---

### 1. Shape

```python
A.shape
```

Output

```text
(2, 2)
```

---

### 2. Matrix Addition

```python
A + B
```

Output

```text
[[ 6  8]
 [10 12]]
```

---

### 3. Scalar Multiplication

```python
3 * A
```

Output

```text
[[ 3  6]
 [ 9 12]]
```

---

### 4. Matrix Multiplication

```python
A @ B
```

or

```python
np.matmul(A, B)
```

Output

```text
[[19 22]
 [43 50]]
```

---

### 5. Transpose

```python
A.T
```

Output

```text
[[1 3]
 [2 4]]
```

---

### 6. Identity Matrix

```python
np.eye(3)
```

Output

```text
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

---

### 7. Diagonal Matrix

```python
np.diag([2, 5, 7])
```

Output

```text
[[2 0 0]
 [0 5 0]
 [0 0 7]]
```

---

### 8. Access an Element

```python
A[1, 0]
```

Output

```text
3
```

---

### 9. Access a Row

```python
A[0]
```

Output

```text
[1 2]
```

---

### 10. Access a Column

```python
A[:, 1]
```

Output

```text
[2 4]
```

---

## ML Connection

Almost every ML library uses NumPy-style matrix operations internally.

Examples:

* Dataset (`X`) → Matrix
* Model weights (`W`) → Matrix
* Predictions:

[
Y = XW
]

* Covariance matrices
* PCA
* Neural Networks
* Transformers

Efficient matrix operations are one of the reasons NumPy is so fast and widely used.

---

## Important Note

The functions you'll use most often in AI/ML are:

| Operation             | NumPy                    |
| --------------------- | ------------------------ |
| Create Matrix         | `np.array()`             |
| Shape                 | `.shape`                 |
| Matrix Addition       | `A + B`                  |
| Scalar Multiplication | `k * A`                  |
| Matrix Multiplication | `A @ B` or `np.matmul()` |
| Transpose             | `A.T`                    |
| Identity Matrix       | `np.eye()`               |
| Diagonal Matrix       | `np.diag()`              |
| Magnitude (Vector)    | `np.linalg.norm()`       |
| Dot Product           | `np.dot()`               |

These are the core NumPy operations you'll repeatedly use throughout your AI/ML journey.